services:
  web:
    build: ./flask-app
    ports:
      - "8080:5000"
    environment:
      - APP_SECRET=supersecret
      - DB_HOST=db
      - DB_NAME=flaskdb
      - DB_USER=flaskuser
      - DB_PASS=flaskpass
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
      - POSTGRES_DB=flaskdb
    volumes:
      - dbdata:/var/lib/postresql/data
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  dbdata:

